name = "wist"
version = "0.1.0"
description = "A small, typed, ergonomic WebSocket layer for Gleam applications built on top of Mist"
licences = ["MIT"]
repository = { type = "github", user = "gleam-foundry", repo = "wist" }
links = [{ title = "Hex Docs", href = "https://hexdocs.pm/wist" }]


[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
mist = ">= 6.0.3 and < 7.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
glisten = ">= 9.0.1 and < 10.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gramps = ">= 6.0.1 and < 7.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
